### ISSUE TITLE
Does this tool work?

### ISSUE THREAD

**Issue by mikelortega** [lokal-profil/mapillary2commons#8]
Somehow I do not manage to make it work, stays in the same page.
https://tools.wmflabs.org/mapillary-commons/mapillary2commons/
It seems the Mapillary URLs changed, but I tried with the old URL and it seems that it doesn't work either.
Thank you.

**Comment by lokal-profil** [comment]
I'm not in a position to check right now but @Abbe98 might be able to.

If its a Mapillary issue then maybe @Gyllen knows?

**Comment by Abbe98** [comment]
@mikelortega this tool is broken after a recent change on WMFLabs.

Tool Labs has forced a Content Security Policy on all tools so there is no way we can make client side requests to Mapillary or other third party services anymore without a backend modifying the CSP or acting as a proxy.

I'm unlikely to fix this in the near future.

**Comment by strainu** [comment]
@Abbe98 are you sure this is because of the CSP? The Mapillary requests seem to work OK,, the issue seems to be the fact that search.mapzen has been dead for about an year.

**Comment by Abbe98** [comment]
@strainu I'm pretty sure that was the case, however I will need to spend a few hour migrating code on Tool Labs this weekend anyway so I could look into this. If it's a Mapzen search thing it will be a an easy fix ✔️

**Comment by lokal-profil** [comment]
@Abbe98 I migrated the tool to Stretch before spotting this. I've added you as a maintainer since by now this tool is more your code than mine =)

**Comment by Abbe98** [comment]
@lokal-profil awesome, I will have a look at it once I find the time to finalize my own Stretch migrations.

**Comment by matkoniecz** [comment]
It used to work but nowadays it is broken

**Comment by lokal-profil** [comment]
> It used to work but nowadays it is broken

Looks like something has changed on the Mapillary side :(

**Comment by lokal-profil** [comment]
See  #11
